### ISSUE TITLE
.env does not loading.

### ISSUE THREAD

**Issue by gem3** [leafsphp/leafAPI#11]
Hello, I'm trying to make "Your first Leaf API" in doc.

I faced a error in "Using our model" section.

`
public function index() {
  $this->respond(Post::all());
}
`
Fatal error:
`
Uncaught InvalidArgu
Fatal error: Uncaught InvalidArgumentException: Unsupported driver [] in /demo/vendor/illuminate/database/Connectors/ConnectionFactory.php:285 Stack trace: #0 /demo/vendor/illuminate/database/Connectors/ConnectionFactory.php(76): Illuminate\Database\Connectors\ConnectionFactory->createConnection(false, Object(Closure), false, '', Array) #1 /demo/vendor/illuminate/database/Connectors/ConnectionFactory.php(50): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array) #2 /demo/vendor/illuminate/database/DatabaseManager.php(131): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'default') #3 /demo/vendor/illuminate/database/DatabaseManager.php(86): Illuminate\Database\DatabaseManager->makeConnection('default') #4 /demo/vendor/illuminate/database/Eloquent/Model.php(1257): Illuminate\Database\DatabaseManager->connection('defaul in /demo/vendor/illuminate/database/Connectors/ConnectionFactory.php on line 285
`

It looks like .env does not loading.

So I put 
`
\Dotenv\Dotenv::create(__DIR__)->load();
`
in index.php just after
`
require_once __DIR__ . '/vendor/autoload.php';
`
Is this right way to fix this error?

**Comment by mychidarko** [comment]
Hi @gem3, sorry about your issue. Which version of Leaf API are you using pls?

**Comment by gem3** [comment]
Hello @darko-mychi.
I'm using ver 1.1.

**Comment by mychidarko** [comment]
Oh alright, but this issue, and all other issues you may encounter in v1.1 have been fixed in v2.0 which was released recently. So I'll recommend you upgrade immediately. Thanks and sorry for your issue😇

**Comment by gem3** [comment]
Hello @darko-mychi.

Thank you for your reply. I will try to use v2.0.
