### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by ghena** [leafsphp/leafAPI#13]
Hi on windows running on php 7.3.1 I have an error:

Parse error: syntax error, unexpected '\' (T_NS_SEPARATOR), expecting function (T_FUNCTION) or const (T_CONST) in \leaf\api\vendor\leafs\leaf\src\App.php on line 21

Regards.
g.

**Comment by darko-mychi** [comment]
Can you pls show your code pls

**Comment by mychidarko** [comment]
Hi @ghena, this issue along with a few more affecting PHP 7.3 have been resolved. You can update your Leaf version to the latest to fix this now. Just run `composer require leafs/leaf` in your project root.
