### ISSUE TITLE
error migrating files

### ISSUE THREAD

**Issue by MahmudSuleman** [leafsphp/leafAPI#14]
hello, please this is my first time using this framework and i am having issues with my first migration, below is a screenshot of the error.
![Screenshot (29)](https://user-images.githubusercontent.com/38923023/127379815-18ac3e1b-564b-4707-a835-f2a069e9b629.png)

below is my composer.json file 
![Screenshot (30)](https://user-images.githubusercontent.com/38923023/127380150-cdd13bbe-0bbd-4ac3-bdfb-3145ba2e9293.png)

**Comment by mychidarko** [comment]
<img width="579" alt="image" src="https://user-images.githubusercontent.com/26604242/129807075-971cc2b7-b2b4-4166-96ce-3ee83747cec6.png">

Please try this. And sorry for the late reply.
