### ISSUE TITLE
Connection refused with db port other than 3306

### ISSUE THREAD

**Issue by fonnets** [leafsphp/leafAPI#17]
Hi, my local mysql database is on a port other than 3306 (on Mamp Pro is 8889), setting the port on the .env file to 8889 the connection is refused. I tried to change the MySql port to 3306 and in this case the connection works correctly. I don't understand why DB_HOST, DB_DATABASE, DB_USERNAME and DB_PASSWORD are correctly retrieved, while DB_PORT (and probably all environment variables that enter the pdoOptions array) are not retrieved from the .env file.

Maybe I'm missing something or is it a bug?
I am using Leaf version 3 with Db version 2

The environment variable of the DB_PORT is null, as if it were not set, in that case it tries to connect to port 3306 by default, returning this error:

PDOException thrown with message "SQLSTATE[HY000] [2002] Connection refused"

Stacktrace:
#9 PDOException in /vendor/leafs/db/src/Db/Core.php:134
#8 PDO:__construct in /vendor/leafs/db/src/Db/Core.php:134
#7 Leaf\Db\Core:connect in /vendor/leafs/auth/src/Auth/Core.php:79
#6 Leaf\Auth\Core:connect in /vendor/leafs/auth/src/Auth/Core.php:91
#5 Leaf\Auth\Core:autoConnect in /app/controllers/Controller.php:20
#4 App\Controllers\Controller:__construct in /vendor/leafs/router/src/Router/Core.php:458
#3 Leaf\Router\Core:invoke in /vendor/leafs/router/src/Router/Core.php:424
#2 Leaf\Router\Core:handle in /vendor/leafs/router/src/Router/Core.php:356
#1 Leaf\Router\Core:run in /public/index.php:130
#0 require_once in /index.php:24

Thanks

**Comment by mychidarko** [comment]
Wow, thanks for opening this

**Comment by mychidarko** [comment]
I'll check it out and let you know my findings

**Comment by mychidarko** [comment]
Just noticed this issue was never updated. This was fixed in v2.0.2 of Leaf DB. Changelog @ https://github.com/leafsphp/db/releases/tag/v2.0.2
