### ISSUE TITLE
apiResource method not found

### ISSUE THREAD

**Issue by swimitup** [leafsphp/leafAPI#18]
Clean leafAPI clone installation.

Follow docs. Tried to use the apiResource method instead of resource:

![Screen Shot 2022-09-16 at 3 33 40 PM](https://user-images.githubusercontent.com/12404245/190789678-2dfac9a6-6dea-4c72-8a6a-5a9cf898e167.png)

Reference:
https://api.leafphp.dev/docs/core/controllers.html#resource-controllers

How is your reference showing a method that is not in code? I mean, you have to have this code somewhere. Is this repository updated from the main one?

**Comment by mychidarko** [comment]
Hi @swimitup just noticed this. It's from a Leaf router update. I'll have this corrected, sorry for the inconvenience.

**Comment by mychidarko** [comment]
This has been fixed now. You can run `leaf install router` or `composer require leafs/router`. That would get rid of the problem in your project.
