### ISSUE TITLE
Auto docs of api

### ISSUE THREAD

**Issue by MauMaxxa** [leafsphp/leafAPI#4]
Hi Mychi, and thank you first of all For your wonderful work!

I'd like to use your LeafAPI, but i have one question: does it implements some auto doc like swagger of similar?

Also, can you provide an example with some models, authorization, permission? This is the tipical need of a rest api, and it would be really useful For anybody that want to use leafAPI..
Thank you!
Mauro

**Comment by mr-phlames** [comment]
Hi @MauMaxxa, thanks for your interest in Leaf and Leaf API. Unfortunately, it doesn't implement swagger or anything similar.

Also thanks for your suggestion on the examples. I'll share some snippets on the code labs section of the documentation when I have them organised. Good luck on your project.

**Comment by MauMaxxa** [comment]
Hi @mr-phlames , and thank you for your kind reply!
Do you have plans about implement auto-documentation features?

Thank you for your wonderful work!
Looking forward to hear from you!
Mauro

**Comment by mr-phlames** [comment]
Well, I've actually never explored any auto doc feature, so I'll need more insight on it before I can think of implementing anything like that....which might take some time, so no promises there😢

**Comment by MauMaxxa** [comment]
Me too i never tried, but swagger php seems easy to implement in your structure!
I'd like to contribute to leaf, if i'd be able to!
If you could please provide an example of api like users/todos or similar, simple but "true life" example of leaf api, i'll be happy to contribute!!

**Comment by mr-phlames** [comment]
Sure, contributors are always welcome! It seems the example is more important than I thought😅 I'll have one ready for you in a while

**Comment by MauMaxxa** [comment]
Yeah, examples are crucial for beginners 😅
Thank you!
