### ISSUE TITLE
Response code not working

### ISSUE THREAD

**Issue by OtaHofmann** [leafsphp/leafAPI#7]
Hi :-)
I would like to ask you about response code. When I am using respondWithCode with any argument except 200 then my response still have 200. 
I tried go another way and set code manually (setCode(401))

Code in json message is ok.

Am I doing something wrong?
Thank you

**Comment by mychidarko** [comment]
Hi @OtaHofmann, sorry for the delayed response. This particular issue has been fixed in the latest version of Leaf. What version of leafs/leaf is in your composer.json file?

**Comment by OtaHofmann** [comment]
Hi @darko-mychi 
Thank you for your response. Version update resolved the problem 👍

**Comment by mychidarko** [comment]
@OtaHofmann Glad I could help
